// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxuJfUYCdGv9x6RlqJ35XJPcsVLwoSFxU',
    appId: '1:816495285505:web:5b2c5e2122a800f88ef700',
    messagingSenderId: '816495285505',
    projectId: 'medical-app-new-version',
    authDomain: 'medical-app-new-version.firebaseapp.com',
    storageBucket: 'medical-app-new-version.appspot.com',
    measurementId: 'G-L30HPS75MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-z4QMDXw3x_kQ3CJ7kkXMHRbdiLUM3X8',
    appId: '1:816495285505:android:32607ae86c6cc0848ef700',
    messagingSenderId: '816495285505',
    projectId: 'medical-app-new-version',
    storageBucket: 'medical-app-new-version.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrLXuZdOI9yTDA80zYHI-7EVM3htVrHUI',
    appId: '1:816495285505:ios:638d38e59df3acd68ef700',
    messagingSenderId: '816495285505',
    projectId: 'medical-app-new-version',
    storageBucket: 'medical-app-new-version.appspot.com',
    iosBundleId: 'com.example.medicalAppNewVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxuJfUYCdGv9x6RlqJ35XJPcsVLwoSFxU',
    appId: '1:816495285505:web:e1a17e5c3504ba348ef700',
    messagingSenderId: '816495285505',
    projectId: 'medical-app-new-version',
    authDomain: 'medical-app-new-version.firebaseapp.com',
    storageBucket: 'medical-app-new-version.appspot.com',
    measurementId: 'G-PFBK9HE38J',
  );
}
